title: <p align="center"> Bruno Raimundo </p>

logo: "/images/Fotografia.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_Bruno_Raimundo [ENG].pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/brunoraimundo/">LinkedIn</a> |
  <a href="https://github.com/brunoraimundo93">GitHub</a>
  </p>
  
  <p align="justify">
  👋 Hi there, I'm Bruno Raimundo. <br/><br/>
  I'm a mechanical engineer with a mind for logistics and a heart for data. From factory floors to digital dashboards, I thrive on driving digital transformation by making complex systems run better — finding clarity in chaos and turning numbers into decisions that fuel innovation and progress.

  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-PSW1MY7HB4 # Google Analytics tracking ID
