title: <p align="center"> Bruno Raimundo </p>

logo: "/images/Fotografia.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/CV_Bruno_Raimundo [ENG].pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/brunoraimundo/">LinkedIn</a> |
  <a href="https://github.com/brunoraimundo93">GitHub</a>
  </p>
  
  <p align="justify">
  👋 Hi there, I'm Bruno Raimundo. <br/><br/>
  I'm a mechanical engineer with a passion for logistics and a strong drive for data. From optimizing operational workflows to leveraging data for strategic decisions, I thrive on transforming complex challenges into clear, actionable insights. With a focus on data-driven decision-making, I help organizations unlock growth, drive innovation, and turn data into impactful solutions.

  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-PSW1MY7HB4 # Google Analytics tracking ID
